#+title: Game Design Document

* Project Description
This game design document describes details and ideas behind the 2D platformer + 3-in-a-row game.

The game's setting is gloomy-cyberpunk-(maybe soviet) wastelands with mere electricity left.

The name is not defined yet, but the candidate names are:
- Berow (bevy + 3-in-a-row)
- Stories of Light
- Bevolt (bevy + voltage)
- Path of Electron
- Project Light

* Characters

** El
- main character, joung engineer with MBT-tool.
** Dar
- an old man, head of the village.
** Javis
- a young man from the same village, knows one man from the expidition.
** Rustan
- head of the expidition.

* Storyline
A young woman engineer El comes on her own to Snake island, on which one can barely see any light. Due to unforeseen circumstances, her boat crashes into the rocks and she climbs out of it. Then she finds a bascule bridge to the village, which unfortunately is lifted. She tries to use her Modified Ball of Tesla (MBT), which can generate electricity, to power it, but the tool breaks and can no more generate sufficient energy to power the bridge. Dar, the local head, notices her and uses a lever to open a passage, built entirely out of wood. Then he brings her to the city center, where people are already gathered to meet her. Dar tells her the story of the island: for more than two years the main power-generating station is not working and all the engineers are missing. Then a young man Javis shows up and tells her about a recent expedition with Rustan as a head to find out what is wrong. However, no one heard about them for nearly 3 months. El asks if there are any remaining documents left nearby that can give some clues. Javis says that all the papers are in a building with an electrical door lock and they have no access to it. El tells them about MBT and how she thinks she can fix the lock. Then El follows Javis to the building and with simple combinations she opens the door. Then she sees a map of the expedition and the story begins.
* Theme
The game is about fighting for a better future and never sitting back when the matter is your people's future. The game should underline the importance of each one's contribution to a bigger plan and give a sense of "coziness" when people are together, even though the world outside is gloomy and cold.
